### PR TITLE
Add perk to share access with debater role

### PR DESCRIPTION
**Pull request by fuenkchen**
Can be tested on love
* for editors, supporters and admins a new access campaign should appear at `/teilen``
* after granting access recipient should receive invitation mail, after claiming access, granter should receive confirmation mail
* the role `debater` should be added to recipient

When deploying we need to execute the an SQL statement to add suitable access campaign, can be reviewed as well :)
```
INSERT INTO "accessCampaigns"("title","description","grantPeriodInterval","emailFollowup","beginAt","endAt","constraints","createdAt","updatedAt","grantClaimableInterval","config")
VALUES
('Autorinnen im Dialog 🦄','Abonnement teilen, um externen Autoren einen 21-tägigen Zugriff und die Möglichkeit zu geben, aktiv am Dialog teilzunehmen.','21 days','7 days','2021-06-28 08:30:00+00','2050-01-01 00:00:00+00','[{"limitSlots": {"slots": 100}}, {"limitRevokedSlots": {"slots": 100}}, {"recipientInNoSlot": {}}, {"requireRole": {"roles": ["editor", "supporter", "admin"]}}]',now(),now(),'30 days','{"perks": [{"accessWithRole": {"role": "debater"}}], "emails": [{"party": "recipient", "enabled": true, "template": "invitation"}, {"party": "granter", "enabled": true, "template": "claim_notice"}, {"party": "recipient", "enabled": false, "template": "onboarding"}, {"party": "recipient", "enabled": false, "template": "expired"}, {"party": "recipient", "enabled": false, "template": "followup"}]}');
```

### CODE REVIEW

**Comment by patrickvenetz** [comment]
Testing on Love:

- [x] Invite author, author can debate
- [x] Author can no longer debate after access grant expired
- [x] Invite author with existing abo, author is notified about it
- [x] Regular user won't see campaign in /teilen
- [x] Author can't be invited twice unless previous access grant expired

**Review by patrickvenetz — COMMENTED** [review]
I like your work.

Would strip some more business logic in perk and stick to what perk name promises: access with role. Also translation keys in perk needs its their namespace.

**Comment by fuenkchen** [comment]
Tested on love: 
* `beginAt` = date in future, appears as soon as date is reached (SQL statement above is updated)

**Review by patrickvenetz — APPROVED** [review]
LGTM

**Pull request merged**
